{!! view('analytics::tracker.reporters.bounce_rate')->render() !!}
{!! view('analytics::tracker.reporters.copy_paste')->render() !!}
{!! view('analytics::tracker.reporters.engagement')->render() !!}
{!! view('analytics::tracker.reporters.exit_rate')->render() !!}
{!! view('analytics::tracker.reporters.file_downloads')->render() !!}
{!! view('analytics::tracker.reporters.form_interactions')->render() !!}
{!! view('analytics::tracker.reporters.form_submissions')->render() !!}
{!! view('analytics::tracker.reporters.geolocation')->render() !!}
{!! view('analytics::tracker.reporters.gpu_errors')->render() !!}
{!! view('analytics::tracker.reporters.heatmap')->render() !!}
{!! view('analytics::tracker.reporters.js_errors')->render() !!}
{!! view('analytics::tracker.reporters.media_interactions')->render() !!}
{!! view('analytics::tracker.reporters.mouse_movements')->render() !!}
{!! view('analytics::tracker.reporters.outbound_links')->render() !!}
{!! view('analytics::tracker.reporters.scroll_depth')->render() !!}
{!! view('analytics::tracker.reporters.search_interactions')->render() !!}
{!! view('analytics::tracker.reporters.time_on_page')->render() !!}
{!! view('analytics::tracker.reporters.user_frustration')->render() !!}
{!! view('analytics::tracker.reporters.user_inactivity')->render() !!}
{!! view('analytics::tracker.reporters.video_reporting')->render() !!}
{!! view('analytics::tracker.reporters.viewport')->render() !!}
{!! view('analytics::tracker.reporters.ads')->render() !!}
{!! view('analytics::tracker.reporters.tab_visibility')->render() !!}
{!! view('analytics::tracker.reporters.wordpress_interactions')->render() !!}
